name: Deploy to Clever Cloud
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Clever Cloud Redeploy
        run: |
          curl -X GET "https://api.clever-cloud.com/v2/github/redeploy?appId=app_a2138b56-48d2-4d1a-a28e-1aa8425e9298&secret=${{ secrets.CLEVER_APP_SECRET }}"